# Generated by Django 4.2.6 on 2023-11-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isEditing',
            field=models.BooleanField(default=False),
        ),
    ]
