# Generated by Django 4.2.6 on 2023-11-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_isediting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='taskId',
        ),
    ]
